package com.sparking.hibernate;

// Generated Apr 23, 2015 9:36:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Spot generated by hbm2java
 */
@Entity
@Table(name = "Spot", catalog = "spark")
public class Spot implements java.io.Serializable {

	private Integer spotId;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String zip;
	private String spotType;
	private String rateHr;
	private String rateMonthly;
	private String description;
	private Integer carSize;
	private Double x1;
	private Double y1;
	private String image;
	private String spotBooked;

	public Spot() {
	}

	public Spot(String address1, String city, String state, String zip,
			String spotType, String rateHr, String rateMonthly) {
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.spotType = spotType;
		this.rateHr = rateHr;
		this.rateMonthly = rateMonthly;
	}

	public Spot(String address1, String address2, String city, String state,
			String zip, String spotType, String rateHr, String rateMonthly,
			String description, Integer carSize, Double x1, Double y1) {
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.spotType = spotType;
		this.rateHr = rateHr;
		this.rateMonthly = rateMonthly;
		this.description = description;
		this.carSize = carSize;
		this.x1=x1;
		this.y1=y1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SpotId", unique = true, nullable = false)
	public Integer getSpotId() {
		return this.spotId;
	}

	public void setSpotId(Integer spotId) {
		this.spotId = spotId;
	}

	@Column(name = "Address1", nullable = false, length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "City", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false, length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Zip", nullable = false, length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "SpotType", nullable = false, length = 45)
	public String getSpotType() {
		return this.spotType;
	}

	public void setSpotType(String spotType) {
		this.spotType = spotType;
	}

	@Column(name = "RateHr", nullable = false, length = 45)
	public String getRateHr() {
		return this.rateHr;
	}

	public void setRateHr(String rateHr) {
		this.rateHr = rateHr;
	}

	@Column(name = "RateMonthly", nullable = false, length = 45)
	public String getRateMonthly() {
		return this.rateMonthly;
	}

	public void setRateMonthly(String rateMonthly) {
		this.rateMonthly = rateMonthly;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CarSize")
	public Integer getCarSize() {
		return this.carSize;
	}

	public void setCarSize(Integer carSize) {
		this.carSize = carSize;
	}
	@Column(name = "X1")
	public Double getX1() {
		return x1;
	}

	public void setX1(Double x1) {
		this.x1 = x1;
	}
	@Column(name = "Y1")
	public Double getY1() {
		return y1;
	}

	public void setY1(Double y1) {
		this.y1 = y1;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getSpotBooked() {
		return spotBooked;
	}

	public void setSpotBooked(String spotBooked) {
		this.spotBooked = spotBooked;
	}

}
