package com.sparking.hibernate;
// Generated Dec 29, 2015 3:09:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spot generated by hbm2java
 */
@Entity
@Table(name = "Spot", catalog = "spark")
public class Spot implements java.io.Serializable {

	private Integer spotId;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String zip;
	private String spotType;
	private String rateHr;
	private String rateMonthly;
	private String description;
	private Integer carSize;
	private String image;
	private BigDecimal x1;
	private BigDecimal y1;
	private String spotBooked;
	private Integer count;
	private String neighborhood;
	private Integer spotOwnerUserId;
	private Date startTime;
	private Date endTime;
	private Date date;
	private Date lastBooked;

	public Spot() {
	}

	public Spot(String address1, String address2, String city, String state, String zip, String spotType, String rateHr,
			String rateMonthly, String description, Integer carSize, String image, BigDecimal x1, BigDecimal y1,
			String spotBooked, Integer count, String neighborhood, Integer spotOwnerUserId, Date startTime,
			Date endTime, Date date, Date lastBooked) {
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.spotType = spotType;
		this.rateHr = rateHr;
		this.rateMonthly = rateMonthly;
		this.description = description;
		this.carSize = carSize;
		this.image = image;
		this.x1 = x1;
		this.y1 = y1;
		this.spotBooked = spotBooked;
		this.count = count;
		this.neighborhood = neighborhood;
		this.spotOwnerUserId = spotOwnerUserId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.date = date;
		this.lastBooked = lastBooked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "spotId", unique = true, nullable = false)
	public Integer getSpotId() {
		return this.spotId;
	}

	public void setSpotId(Integer spotId) {
		this.spotId = spotId;
	}

	@Column(name = "address1", length = 45)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 45)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "spotType", length = 45)
	public String getSpotType() {
		return this.spotType;
	}

	public void setSpotType(String spotType) {
		this.spotType = spotType;
	}

	@Column(name = "rateHr", length = 45)
	public String getRateHr() {
		return this.rateHr;
	}

	public void setRateHr(String rateHr) {
		this.rateHr = rateHr;
	}

	@Column(name = "rateMonthly", length = 45)
	public String getRateMonthly() {
		return this.rateMonthly;
	}

	public void setRateMonthly(String rateMonthly) {
		this.rateMonthly = rateMonthly;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "carSize")
	public Integer getCarSize() {
		return this.carSize;
	}

	public void setCarSize(Integer carSize) {
		this.carSize = carSize;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "x1", precision = 12, scale = 8)
	public BigDecimal getX1() {
		return this.x1;
	}

	public void setX1(BigDecimal x1) {
		this.x1 = x1;
	}

	@Column(name = "y1", precision = 12, scale = 8)
	public BigDecimal getY1() {
		return this.y1;
	}

	public void setY1(BigDecimal y1) {
		this.y1 = y1;
	}

	@Column(name = "spotBooked", length = 5)
	public String getSpotBooked() {
		return this.spotBooked;
	}

	public void setSpotBooked(String spotBooked) {
		this.spotBooked = spotBooked;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "neighborhood", length = 45)
	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	@Column(name = "spotOwnerUserId")
	public Integer getSpotOwnerUserId() {
		return this.spotOwnerUserId;
	}

	public void setSpotOwnerUserId(Integer spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTime", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastBooked", length = 19)
	public Date getLastBooked() {
		return this.lastBooked;
	}

	public void setLastBooked(Date lastBooked) {
		this.lastBooked = lastBooked;
	}

}
