package com.sparking.hibernate;
// Generated Nov 15, 2015 4:44:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Spot generated by hbm2java
 */
@Entity
@Table(name = "Spot", catalog = "spark")
public class Spot implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer spotId;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String zip;
	private String spotType;
	private String rateHr;
	private String rateMonthly;
	private String description;
	private Integer carSize;
	private String image;
	private Long x1;
	private Long y1;
	private String spotBooked;
	private Integer count;
	private String neighborhood;
	private int spotOwnerUserId;

	public Spot() {
	}

	public Spot(int spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}
	/**
	 * Spot object returned
	 * @param address1
	 * @param address2
	 * @param city
	 * @param state
	 * @param zip
	 * @param spotType
	 * @param rateHr
	 * @param rateMonthly
	 * @param description
	 * @param carSize
	 * @param image
	 * @param x1
	 * @param y1
	 * @param spotBooked
	 * @param count
	 * @param neighborhood
	 * @param spotOwnerUserId
	 */
	public Spot(String address1, String address2, String city, String state, String zip, String spotType, String rateHr,
			String rateMonthly, String description, Integer carSize, String image, Long x1, Long y1, String spotBooked,
			Integer count, String neighborhood, int spotOwnerUserId) {
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.spotType = spotType;
		this.rateHr = rateHr;
		this.rateMonthly = rateMonthly;
		this.description = description;
		this.carSize = carSize;
		this.image = image;
		this.x1 = x1;
		this.y1 = y1;
		this.spotBooked = spotBooked;
		this.count = count;
		this.neighborhood = neighborhood;
		this.spotOwnerUserId = spotOwnerUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "spotId", unique = true, nullable = false)
	public Integer getSpotId() {
		return this.spotId;
	}

	public void setSpotId(Integer spotId) {
		this.spotId = spotId;
	}

	@Column(name = "address1", length = 45)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 45)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "spotType", length = 45)
	public String getSpotType() {
		return this.spotType;
	}

	public void setSpotType(String spotType) {
		this.spotType = spotType;
	}

	@Column(name = "rateHr", length = 45)
	public String getRateHr() {
		return this.rateHr;
	}

	public void setRateHr(String rateHr) {
		this.rateHr = rateHr;
	}

	@Column(name = "rateMonthly", length = 45)
	public String getRateMonthly() {
		return this.rateMonthly;
	}

	public void setRateMonthly(String rateMonthly) {
		this.rateMonthly = rateMonthly;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "carSize")
	public Integer getCarSize() {
		return this.carSize;
	}

	public void setCarSize(Integer carSize) {
		this.carSize = carSize;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "x1", precision = 10, scale = 0)
	public Long getX1() {
		return this.x1;
	}

	public void setX1(Long x1) {
		this.x1 = x1;
	}

	@Column(name = "y1", precision = 10, scale = 0)
	public Long getY1() {
		return this.y1;
	}

	public void setY1(Long y1) {
		this.y1 = y1;
	}

	@Column(name = "spotBooked", length = 5)
	public String getSpotBooked() {
		return this.spotBooked;
	}

	public void setSpotBooked(String spotBooked) {
		this.spotBooked = spotBooked;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "neighborhood", length = 45)
	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	@Column(name = "spotOwnerUserId", nullable = false)
	public int getSpotOwnerUserId() {
		return this.spotOwnerUserId;
	}

	public void setSpotOwnerUserId(int spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}

}
