package com.sparking.hibernate;

// Generated Apr 23, 2015 9:36:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StreetSegements generated by hbm2java
 */
@Entity
@Table(name = "STREET_SEGEMENTS", catalog = "spark")
public class StreetSegements implements java.io.Serializable {

	private Integer streetSegmentId;
	private String x1;
	private String y1;
	private String x2;
	private String y2;
	private Integer maxCapacity;
	private Integer parkedCount;

	public StreetSegements() {
	}

	public StreetSegements(String x1, String y1, String x2, String y2,
			Integer maxCapacity, Integer parkedCount) {
		this.x1 = x1;
		this.y1 = y1;
		this.x2 = x2;
		this.y2 = y2;
		this.maxCapacity = maxCapacity;
		this.parkedCount = parkedCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "StreetSegmentId", unique = true, nullable = false)
	public Integer getStreetSegmentId() {
		return this.streetSegmentId;
	}

	public void setStreetSegmentId(Integer streetSegmentId) {
		this.streetSegmentId = streetSegmentId;
	}

	@Column(name = "X1", length = 45)
	public String getX1() {
		return this.x1;
	}

	public void setX1(String x1) {
		this.x1 = x1;
	}

	@Column(name = "Y1", length = 45)
	public String getY1() {
		return this.y1;
	}

	public void setY1(String y1) {
		this.y1 = y1;
	}

	@Column(name = "X2", length = 45)
	public String getX2() {
		return this.x2;
	}

	public void setX2(String x2) {
		this.x2 = x2;
	}

	@Column(name = "Y2", length = 45)
	public String getY2() {
		return this.y2;
	}

	public void setY2(String y2) {
		this.y2 = y2;
	}

	@Column(name = "MaxCapacity")
	public Integer getMaxCapacity() {
		return this.maxCapacity;
	}

	public void setMaxCapacity(Integer maxCapacity) {
		this.maxCapacity = maxCapacity;
	}

	@Column(name = "ParkedCount")
	public Integer getParkedCount() {
		return this.parkedCount;
	}

	public void setParkedCount(Integer parkedCount) {
		this.parkedCount = parkedCount;
	}

}
