package com.sparking.hibernate;
// Generated Dec 29, 2015 3:09:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txn generated by hbm2java
 */
@Entity
@Table(name = "Txn", catalog = "spark")
public class Txn implements java.io.Serializable {

	private Integer transactionId;
	private int userId;
	private int spotId;
	private String txnAmt;
	private String pmtMethod;
	private Integer userRating;
	private Integer spotRating;
	private String spotType;
	private int spotOwnerUserId;
	private Date date;
	private Date startTime;
	private Date endTime;
	private String vehicleLicense;
	private String paymentMethodNonce;

	public Txn() {
	}

	public Txn(int userId, int spotId, int spotOwnerUserId) {
		this.userId = userId;
		this.spotId = spotId;
		this.spotOwnerUserId = spotOwnerUserId;
	}

	public Txn(int userId, int spotId, String txnAmt, String pmtMethod, Integer userRating, Integer spotRating,
			String spotType, int spotOwnerUserId, Date date, Date startTime, Date endTime, String vehicleLicense,
			String paymentMethodNonce) {
		this.userId = userId;
		this.spotId = spotId;
		this.txnAmt = txnAmt;
		this.pmtMethod = pmtMethod;
		this.userRating = userRating;
		this.spotRating = spotRating;
		this.spotType = spotType;
		this.spotOwnerUserId = spotOwnerUserId;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
		this.vehicleLicense = vehicleLicense;
		this.paymentMethodNonce = paymentMethodNonce;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "transactionId", unique = true, nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "spotId", nullable = false)
	public int getSpotId() {
		return this.spotId;
	}

	public void setSpotId(int spotId) {
		this.spotId = spotId;
	}

	@Column(name = "txn_amt", length = 45)
	public String getTxnAmt() {
		return this.txnAmt;
	}

	public void setTxnAmt(String txnAmt) {
		this.txnAmt = txnAmt;
	}

	@Column(name = "pmt_method", length = 45)
	public String getPmtMethod() {
		return this.pmtMethod;
	}

	public void setPmtMethod(String pmtMethod) {
		this.pmtMethod = pmtMethod;
	}

	@Column(name = "user_rating")
	public Integer getUserRating() {
		return this.userRating;
	}

	public void setUserRating(Integer userRating) {
		this.userRating = userRating;
	}

	@Column(name = "spot_rating")
	public Integer getSpotRating() {
		return this.spotRating;
	}

	public void setSpotRating(Integer spotRating) {
		this.spotRating = spotRating;
	}

	@Column(name = "spot_type", length = 45)
	public String getSpotType() {
		return this.spotType;
	}

	public void setSpotType(String spotType) {
		this.spotType = spotType;
	}

	@Column(name = "spotOwnerUserId", nullable = false)
	public int getSpotOwnerUserId() {
		return this.spotOwnerUserId;
	}

	public void setSpotOwnerUserId(int spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "vehicle_license", length = 45)
	public String getVehicleLicense() {
		return this.vehicleLicense;
	}

	public void setVehicleLicense(String vehicleLicense) {
		this.vehicleLicense = vehicleLicense;
	}

	@Column(name = "paymentMethodNonce", length = 45)
	public String getPaymentMethodNonce() {
		return this.paymentMethodNonce;
	}

	public void setPaymentMethodNonce(String paymentMethodNonce) {
		this.paymentMethodNonce = paymentMethodNonce;
	}

}
