package com.sparking.hibernate;
// Generated Nov 15, 2015 4:44:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Txn generated by hbm2java
 */
@Entity
@Table(name = "Txn", catalog = "spark")
public class Txn implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer transactionId;
	private Integer userId;
	private Integer spotId;
	private String txnAmt;
	private String pmtMethod;
	private Integer userRating;
	private Integer spotRating;
	private String spotType;
	private int spotOwnerUserId;

	public Txn() {
	}

	public Txn(int spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}
/**
 * Transaction object
 * @param userId
 * @param spotId
 * @param txnAmt
 * @param pmtMethod
 * @param userRating
 * @param spotRating
 * @param spotType
 * @param spotOwnerUserId
 */
	public Txn(Integer userId, Integer spotId, String txnAmt, String pmtMethod, Integer userRating, Integer spotRating,
			String spotType, int spotOwnerUserId) {
		this.userId = userId;
		this.spotId = spotId;
		this.txnAmt = txnAmt;
		this.pmtMethod = pmtMethod;
		this.userRating = userRating;
		this.spotRating = spotRating;
		this.spotType = spotType;
		this.spotOwnerUserId = spotOwnerUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "transactionId", unique = true, nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "spotId")
	public Integer getSpotId() {
		return this.spotId;
	}

	public void setSpotId(Integer spotId) {
		this.spotId = spotId;
	}

	@Column(name = "txn_amt", length = 45)
	public String getTxnAmt() {
		return this.txnAmt;
	}

	public void setTxnAmt(String txnAmt) {
		this.txnAmt = txnAmt;
	}

	@Column(name = "pmt_method", length = 45)
	public String getPmtMethod() {
		return this.pmtMethod;
	}

	public void setPmtMethod(String pmtMethod) {
		this.pmtMethod = pmtMethod;
	}

	@Column(name = "user_rating")
	public Integer getUserRating() {
		return this.userRating;
	}

	public void setUserRating(Integer userRating) {
		this.userRating = userRating;
	}

	@Column(name = "spot_rating")
	public Integer getSpotRating() {
		return this.spotRating;
	}

	public void setSpotRating(Integer spotRating) {
		this.spotRating = spotRating;
	}

	@Column(name = "spot_type", length = 45)
	public String getSpotType() {
		return this.spotType;
	}

	public void setSpotType(String spotType) {
		this.spotType = spotType;
	}

	@Column(name = "spotOwnerUserId", nullable = false)
	public int getSpotOwnerUserId() {
		return this.spotOwnerUserId;
	}

	public void setSpotOwnerUserId(int spotOwnerUserId) {
		this.spotOwnerUserId = spotOwnerUserId;
	}

}
