package com.sparking.hibernate;
// Generated Dec 29, 2015 3:09:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "spark", uniqueConstraints = @UniqueConstraint(columnNames = "fbId") )
public class User implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private String dlicense;
	private String vlicense;
	private String spotTime;
	private String spotId;
	private String zip;
	private String neighborhood;
	private String type;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private Date date;
	private String fbId;
	private String displayPic;

	public User() {
	}

	public User(String firstName, String email) {
		this.firstName = firstName;
		this.email = email;
	}

	public User(String firstName, String lastName, String email, String phone, String dlicense, String vlicense,
			String spotTime, String spotId, String zip, String neighborhood, String type, String addressLine1,
			String addressLine2, String city, String state, Date date, String fbId, String displayPic) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.dlicense = dlicense;
		this.vlicense = vlicense;
		this.spotTime = spotTime;
		this.spotId = spotId;
		this.zip = zip;
		this.neighborhood = neighborhood;
		this.type = type;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.date = date;
		this.fbId = fbId;
		this.displayPic = displayPic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "dLicense", length = 45)
	public String getDlicense() {
		return this.dlicense;
	}

	public void setDlicense(String dlicense) {
		this.dlicense = dlicense;
	}

	@Column(name = "vLicense", length = 45)
	public String getVlicense() {
		return this.vlicense;
	}

	public void setVlicense(String vlicense) {
		this.vlicense = vlicense;
	}

	@Column(name = "spotTime", length = 45)
	public String getSpotTime() {
		return this.spotTime;
	}

	public void setSpotTime(String spotTime) {
		this.spotTime = spotTime;
	}

	@Column(name = "spotId", length = 45)
	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "neighborhood", length = 45)
	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "addressLine1", length = 45)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "addressLine2", length = 45)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "fbId", unique = true, length = 45)
	public String getFbId() {
		return this.fbId;
	}

	public void setFbId(String fbId) {
		this.fbId = fbId;
	}

	@Column(name = "displayPic", length = 300)
	public String getDisplayPic() {
		return this.displayPic;
	}

	public void setDisplayPic(String displayPic) {
		this.displayPic = displayPic;
	}

}
