package com.sparking.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
// Generated Jul 9, 2015 10:30:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "spark")
public class User implements java.io.Serializable {

		private Integer id;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private String dlicense;
	private String vlicense;
	private String spotTime;
	private String spotId;

	public User() {
	}

	

	public User(String firstName, String lastName, String email, String phone,
			String dlicense, String vlicense, String spotTime, String spotId) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.dlicense = dlicense;
		this.vlicense = vlicense;
		this.spotTime = spotTime;
		this.spotId = spotId;
	}
	@Id  
	@Column(name = "Id", unique = true, nullable = false)  
	@GeneratedValue(strategy = GenerationType.AUTO) 
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDlicense() {
		return this.dlicense;
	}

	public void setDlicense(String dlicense) {
		this.dlicense = dlicense;
	}

	public String getVlicense() {
		return this.vlicense;
	}

	public void setVlicense(String vlicense) {
		this.vlicense = vlicense;
	}

	public String getSpotTime() {
		return this.spotTime;
	}

	public void setSpotTime(String spotTime) {
		this.spotTime = spotTime;
	}

	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

}
